services:
  backend:
    container_name: gochat_api
    build: .
    depends_on:
      - rabbitmq
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: no
    environment:
      - APP_PORT=${APP_PORT}

      # jwt
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXP=${JWT_ACCESS_EXP}
      - JWT_REFRESH_EXP=${JWT_REFRESH_EXP}

      # database
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}

      # rabbitmq
      - MQ_USER=${MQ_USER}
      - MQ_PASSWORD=${MQ_PASSWORD}
      - MQ_PORT=${MQ_PORT}
      - MQ_VHOST=${MQ_VHOST}

  rabbitmq: 
    container_name: gochat_mq
    image: rabbitmq:3-management
    ports:
      - ${MQ_PORT}:${MQ_PORT} # for AMQP
      - 15672:15672 # UI management
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${MQ_VHOST}
    volumes:
      - mq_data:/var/lib/rabbitmq

  db:
    container_name: gochat_db
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - db_data:/var/lib/postgresql/data    
    restart: no

volumes:
  db_data:
  mq_data: